name: Java CI with Gradle

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install Gradle 9.0
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 9.0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT
        run: java -jar ./artifacts/app-order.jar &
      - name: Build with Gradle
        run: ./gradlew test --info -Dselenide.headless=true --warning-mode all
      - name: Stop SUT
        run: sudo pkill -f 'java -jar ./artifacts/app-order.jar'